# Generated by Django 5.2.12 on 2026-03-18 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizational", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimport",
            name="imported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="csv_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Imported By",
            ),
        ),
        migrations.AddField(
            model_name="leaderpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="registro",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros",
                to="organizational.csvimport",
                verbose_name="CSV Import",
            ),
        ),
        migrations.AddField(
            model_name="registro",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="organizational.setor",
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="leaderpermission",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_permissions",
                to="organizational.setor",
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="setor",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setores",
                to="organizational.unidade",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="registro",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="organizational.unidade",
                verbose_name="Unidade",
            ),
        ),
        migrations.AddField(
            model_name="leaderpermission",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_permissions",
                to="organizational.unidade",
                verbose_name="Unidade",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="setor",
            unique_together={("name", "unidade")},
        ),
        migrations.AlterUniqueTogether(
            name="registro",
            unique_together={("email", "unidade", "setor")},
        ),
        migrations.AlterUniqueTogether(
            name="leaderpermission",
            unique_together={("user", "unidade", "setor")},
        ),
    ]
