# Generated by Django 5.2.12 on 2026-03-18 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("ACTIVE", "Ativa"),
                            ("CLOSED", "Encerrada"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campanha",
                "verbose_name_plural": "Campanhas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DimensionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Score (0–4)"
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Score de Risco (0–4)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("ACEITAVEL", "Aceitável"),
                            ("MODERADO", "Moderado"),
                            ("IMPORTANTE", "Importante"),
                            ("CRITICO", "Crítico"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Nível de Risco",
                    ),
                ),
                (
                    "unidade_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "setor_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_index=True, max_length=4, null=True
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Score de Dimensão",
                "verbose_name_plural": "Scores de Dimensão",
            },
        ),
        migrations.CreateModel(
            name="HSEDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[("POSITIVE", "Positiva"), ("NEGATIVE", "Negativa")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Dimensão HSE",
                "verbose_name_plural": "Dimensões HSE",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HSEQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texto da Pergunta")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Pergunta HSE",
                "verbose_name_plural": "Perguntas HSE",
                "ordering": ["dimension__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(verbose_name="Valor")),
            ],
            options={
                "verbose_name": "Resposta de Pergunta",
                "verbose_name_plural": "Respostas de Perguntas",
            },
        ),
        migrations.CreateModel(
            name="SurveyInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Hash do Email"
                    ),
                ),
                (
                    "registro_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Registro ID"
                    ),
                ),
                (
                    "unidade_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Unidade ID"
                    ),
                ),
                (
                    "setor_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Setor ID"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Falhou"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status de Envio",
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[("PENDING", "Pendente"), ("ANSWERED", "Respondido")],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status de Resposta",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Convite de Pesquisa",
                "verbose_name_plural": "Convites de Pesquisa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("P", "Prefiro não dizer"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UP_TO_25", "Até 25 anos"),
                            ("26_35", "26–35 anos"),
                            ("36_45", "36–45 anos"),
                            ("46_55", "46–55 anos"),
                            ("ABOVE_55", "Acima de 55 anos"),
                            ("PREF", "Prefiro não dizer"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Faixa Etária",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, verbose_name="Consentimento dado"
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resposta de Pesquisa",
                "verbose_name_plural": "Respostas de Pesquisa",
                "ordering": ["-answered_at"],
            },
        ),
    ]
