# Generated by Django 5.2.12 on 2026-03-18 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="dimensionscore",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimension_scores",
                to="campaigns.campaign",
                verbose_name="Campanha",
            ),
        ),
        migrations.AddField(
            model_name="dimensionscore",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="campaigns.hsedimension",
                verbose_name="Dimensão",
            ),
        ),
        migrations.AddField(
            model_name="hsequestion",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="campaigns.hsedimension",
                verbose_name="Dimensão",
            ),
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="campaigns.hsequestion",
                verbose_name="Pergunta",
            ),
        ),
        migrations.AddField(
            model_name="surveyinvite",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="campaigns.campaign",
                verbose_name="Campanha",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="campaigns.campaign",
                verbose_name="Campanha",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="invite",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="campaigns.surveyinvite",
                verbose_name="Convite",
            ),
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="campaigns.surveyresponse",
                verbose_name="Resposta",
            ),
        ),
        migrations.AddField(
            model_name="dimensionscore",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimension_scores",
                to="campaigns.surveyresponse",
                verbose_name="Resposta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveyinvite",
            unique_together={("campaign", "email_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="surveyanswer",
            unique_together={("response", "question")},
        ),
        migrations.AddIndex(
            model_name="dimensionscore",
            index=models.Index(
                fields=["campaign", "dimension"], name="campaigns_d_campaig_bbe1cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimensionscore",
            index=models.Index(
                fields=["campaign", "risk_level"], name="campaigns_d_campaig_98b104_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimensionscore",
            index=models.Index(
                fields=["campaign", "unidade_id", "setor_id"],
                name="campaigns_d_campaig_4893a8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dimensionscore",
            unique_together={("response", "dimension")},
        ),
    ]
